### ISSUE TITLE
How to build and run it

### ISSUE THREAD

**Issue by Corgile** [JuanDiegoMontoya/Frogfood#13]
```shell
mkdir build
cd build 
cmake ..
make
sudo ./frogRender
```
### says:

![image](https://github.com/JuanDiegoMontoya/Frogfood/assets/48396880/89a49d45-dbe0-4ac1-82d4-23cf1ccc620d)

```shell
Linux admin 6.2.0-31-generic #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by deccer** [comment]
1) Why are you trying to run it with sudo?
2) Are you running this under wayland?
3) Did you happen to just update your system?

**Comment by Corgile** [comment]
> 1. Why are you trying to run it with sudo?

To exclude the possibility of insufficient authority

> 2. Are you running this under wayland?

sure sir

![image](https://github.com/JuanDiegoMontoya/Frogfood/assets/48396880/b68fdf58-2d29-4943-a7e3-19cfcf982aa0)

> 3. Did you happen to just update your system?

I did (sudo apt uodate ; sudo apt upgrade)

**Comment by deccer** [comment]
2) Hehe, would you mind rebooting and trying it again?
1) glfw should autodetect wayland, but that might be a hint...

we will investigate

**Comment by Corgile** [comment]
> 2. Hehe, would you mind rebooting and trying it again?
> 3. glfw should autodetect wayland, but that might be a hint...
> 
> we will investigate


`reboot` is not working. maybe something wrong with the OpenGL version or drivers.
